### PR TITLE
try to explain nonce space duration from paramters

### PR DESCRIPTION
**Pull request by Georges760**
try to calculate the asic_job_frequency_ms dynamicaly, to be discussed

### CODE REVIEW

**Review by skot — APPROVED** [review]
This is looking good to me. Tested on 204, 401 and 402. Way less invalid work and rejected shares

**Comment by Georges760** [comment]
I will try it on 302 @WantClue sent me, then merge it if OK

**Comment by skot** [comment]
My bitaxeMax (v2.2) isn't working. It never starts hashing. It's been a _long_ time since I tested this, so it might not be this branch causing the problem..

**Comment by skot** [comment]
> My bitaxeMax (v2.2) isn't working. It never starts hashing. It's been a _long_ time since I tested this, so it might not be this branch causing the problem..

fixed this with e7a29f8. 
Tested on 102 (v2.2), 204, 401, and 402

**Comment by Georges760** [comment]
regression came from #192

**Comment by Georges760** [comment]
we can merge it now as it fix BitaxeMax, the Hex will be tested on top of it

**Pull request merged**
