### PR TITLE
Nonce checking

### PR DESCRIPTION
**Pull request by developeralgo8888**
update

### CODE REVIEW

**Comment by benjamin-wilson** [comment]
I think this probably belongs in a JaBIT repo along with any binaries you choose to build, not in the Bitaxe repo.

**Comment by johnny9** [comment]
Binary files aren't appropriate for a github repo. If you can transcribe it to markdown or another text based format that would be much better.

**Comment by johnny9** [comment]
Also, rebase your view so that we don't have all of those merge commits

**Review by johnny9 — CHANGES_REQUESTED** [review]
Please use a text-based format like markdown for documentation if you would like to include it in a git repo. Binary files can't be reviewed or diffed in a human readable way.

**Pull request closed without merging**
