### PR TITLE
add 205 config and remove self test flag 

### PR DESCRIPTION
**Pull request by WantClue**
remove self test flag as we already have it remove for all other models

add 205 config

### CODE REVIEW

**Comment by benjamin-wilson** [comment]
The units should always test on a factory flash

**Comment by benjamin-wilson** [comment]
Please allow discussion for large changes

**Comment by skot** [comment]
@eandersson is this going to break how the CI scripts build factory images?

**Comment by eandersson** [comment]
> @eandersson is this going to break how the CI scripts build factory images?

Yea - we use this for factory, but we could use a different approach for that if needed, but gets tricky if there is a firmware that does not support the test flag.

**Comment by skot** [comment]
Ok, we definitely don't want to remove selftest support from the esp-miner

**Comment by eandersson** [comment]
> Ok, we definitely don't want to remove selftest support from the esp-miner

Let me know if you want me to implement it in the CI, instead of reverting this PR. I would need to know though if there are any models that needs to be excluded from the self test.

**Pull request merged**
