### PR TITLE
Remove swarm support

### PR DESCRIPTION
**Pull request by eandersson**

### CODE REVIEW

**Comment by skot** [comment]
People aren't going to like this. But I still think it's the way to go. Hopefully removing Swarm will encourage contributors to make replacements

**Comment by 19201003080114** [comment]
I suggest providing a replacement app/function/whatever BEFORE removing Swarm completely. 
Bitaxe Viewer Chrome extension good but is not the same.

**Comment by 19201003080114** [comment]
> People aren't going to like this. But I still think it's the way to go. Hopefully removing Swarm will encourage contributors to make replacements

I suggest providing a replacement app/function/whatever BEFORE removing Swarm completely.
Bitaxe Viewer Chrome extension good but is not the same.

**Comment by skot** [comment]
This band-aid is getting ripped off⚡️

**Comment by benjamin-wilson** [comment]
I don't see why we should remove it rather than improve it

**Comment by skot** [comment]
> I don't see why we should remove it rather than improve it

My sense is that it adds a lot of complexity to the project (visually for noobs, maintenance overhead, and technical) for a feature that could be much better served by a separate app.

I still think this would make an awesome web app... But maybe that can't work because of CORS?

**Comment by mrv777** [comment]
I'll gladly help work on an alternative.  I was working on something a few weeks ago, but yeah ran into CORS issues when I tried to host it somewhere for people to try as it wants to access local ips.  So was going to look into making it an electron app...or maybe a native app, but that's more work ;)

**Comment by skot** [comment]
> I'll gladly help work on an alternative. I was working on something a few weeks ago, but yeah ran into CORS issues when I tried to host it somewhere for people to try as it wants to access local ips. So was going to look into making it an electron app...or maybe a native app, but that's more work ;) Was thinking about an umbrel app, but think someone else was working on one and it leaves everyone without an umbrel out, so ditched that

Electron app would be amazing. Hit up @Derekblueeyes on OSMU about his Umbrel management app (called Pluto)... maybe there is some overlap?

**Comment by mutatrum** [comment]
One way of getting around the CORS issue is to have a websocket api instead of a REST api. Browsers don't enforce CORS on websocket connections.

**Pull request closed without merging**
