### PR TITLE
fix: Add sorting of swarm table

### PR DESCRIPTION
**Pull request by mrv777**
fixes item 1 in #217

### CODE REVIEW

**Comment by mrv777** [comment]
This one was a bit more complicated then I thought and needed AI to help with, so may be good to be reviewed well

**Comment by skot** [comment]
I _think_ in the future we're going to 86 swarm in favor of external tools.

**Comment by mrv777** [comment]
Sounds good, I'll leave the swarm page alone for now.  I was just looking through some old issues

**Comment by eandersson** [comment]
Lets drop this one as we are planning on removing this feature.

**Pull request closed without merging**
