### PR TITLE
Add overheat button and change loading service

### PR DESCRIPTION
**Pull request by mrv777**
1. Change the overheat checkbox to a button
2. Improves error handling when loading data
3. Simplifies the loading service

Screenshot

### CODE REVIEW

**Comment by mrv777** [comment]
If @benjamin-wilson can just review the loading service change that would great.  I noticed it wasn't handling errors properly it seemed, I made a change but then AI seemed to have a much cleaner change that still seemed to work for me and looks nicer

**Review by WantClue — APPROVED** [review]

**Review by eandersson — COMMENTED** [review]
I haven't tested it YET, but looks good.

**Comment by skot** [comment]
@mrv777 when you get a chance can you rebase this on master? I'd love to get this merged in.

**Comment by mrv777** [comment]
@skot rebased.  I didn't get to test it with the updated base against a device though

**Comment by skot** [comment]
This is looking great! 
image
image

**Comment by skot** [comment]
I also checked out OTA firmware updates in AP mode -- looks good.

**Pull request merged**
