### PR TITLE
Network resets2

### PR DESCRIPTION
**Pull request by skot**
This change handles two Stratum URL error modes that used to cause us to get into a reboot loop;

- DNS lookup fails
- DNS lookup works, but connect() fails

### CODE REVIEW

**Review by johnny9 — CHANGES_REQUESTED** [review]
Remove commented out code and any comments that are redundant/obvious with the next line of code.

 "Fixes #55" can be added to the body of the commit message and helps with tracking when issues are solved.

**Review by johnny9 — APPROVED** [review]

**Comment by johnny9** [comment]
Recommend squashing the commits

**Comment by benjamin-wilson** [comment]
> Recommend squashing the commits

You can always squash on the merge. GitHub has a nice big button for this.

**Comment by johnny9** [comment]
merge commits aren't great either. Its better to squash manually.

**Comment by skot** [comment]
My git skillz are low. How do I do this again?

**Comment by marsmensch** [comment]
@skot I assume johnny9 means rebasing all feature related commits this way:
https://www.freecodecamp.org/news/git-squash-commits/
Screenshot 2024-01-03 at 21 26 22
Screenshot 2024-01-03 at 21 26 57

**Comment by skot** [comment]
> @skot I assume johnny9 means rebasing all feature related commits this way:
> 
> https://www.freecodecamp.org/news/git-squash-commits/
> 
> Screenshot 2024-01-03 at 21 26 22
> 
> Screenshot 2024-01-03 at 21 26 57

perfect, thanks! I'll give this a try

**Pull request merged**
