### PR TITLE
Overhaul Axeos theme

### PR DESCRIPTION
**Pull request by benjamin-wilson**
Overhaul AxeOs theme to more closely align to the brand identity guidelines. This is a first iteration. 

image

### CODE REVIEW

**Comment by WantClue** [comment]
Looks awesome

**Comment by WhiteyCookie** [comment]
How about an option for different colors? I liked the original blueish color

**Comment by skot** [comment]
OMG this looks amazing. nice work @benjamin-wilson !

I think we should resolve this;
image
Maybe just show the RPM number next to the percentage, without it's own gauge?

**Comment by skot** [comment]
Can we do a tick mark on the gauge to show what the requested voltage is? Something like this?
image

**Comment by skot** [comment]
we could do this with the input voltage too.. showing the nominal in the middle, and then the actual measured voltage with the bar 
image

**Comment by benjamin-wilson** [comment]
At this time there is no easy way to add tick marks to the progress bar. 
https://primeng.org/progressbar

I tried doing it with just css and some divs but it looks a bit busy

**Pull request merged**
