### PR TITLE
Added Bitcoin Statistics to the Dashboard

### PR DESCRIPTION
**Pull request by WhiteyCookie**
statistics

### CODE REVIEW

**Comment by skot** [comment]
For privacy and decentralization I do not want any connections to servers besides the configured stratum server in AxeOS

**Comment by WhiteyCookie** [comment]
Allright then, didn't know that. In that case, PR can be deleted or rejected or idk what github provide

**Comment by skot** [comment]
I think you can close it... But I am still interested in your work on #431 .. can we bring that back?

**Comment by WhiteyCookie** [comment]
The percentage of rejected shares? Sure. In the spirit of Halloween I'll summon and resurrect this PR within the next 24h 😂

**Pull request closed without merging**
