### PR TITLE
fix: Add restart to settings & better disabled state

### PR DESCRIPTION
**Pull request by mrv777**
## Description

- Added the restart button to the settings page as requested here: #440 
- Also changed the disabled state so that save is only enabled if there are changes and restart only enabled if changes saved to prevent accidentally clicking that first

### CODE REVIEW

**Comment by skot** [comment]
The restart button is enabled after I slick save, but it doesn't actually restart the Bitaxe when I click on it.
image

**Comment by skot** [comment]
I'd like to add this functionality to the network tab too 🙏

**Comment by mrv777** [comment]
Sorry about that, simple fix.  Should work now.  I'll add it to the network tab later too

**Comment by mrv777** [comment]
PR updated @skot if you want to test when you get a chance.  I tested the settings page, but haven't had a chance yet to upload the changes to a device again to test the network page changes

**Comment by skot** [comment]
both settings and network work great! I think this is a huge usability improvement, very nice @mrv777

**Review by skot — APPROVED** [review]

**Pull request merged**
