### PR TITLE
feat: easter egg

### PR DESCRIPTION
**Pull request by mrv777**
## Description

- Just a fun easter egg

### CODE REVIEW

**Comment by benjamin-wilson** [comment]
We've got limited space in the www partition - I'd be wary of anything unnecessary

**Comment by benjamin-wilson** [comment]
Perhaps a string that prints to the browser console when you open dev tools?

**Comment by mrv777** [comment]
Sure, I can do that instead

**Comment by mrv777** [comment]
If we want to save space:
https://github.com/skot/ESP-Miner/pull/470

**Comment by skot** [comment]
I think we should keep this

**Comment by eandersson** [comment]
LGTM 🗡️

**Pull request closed without merging**
