### PR TITLE
fix: Temp suffix & 5v marker

### PR DESCRIPTION
**Pull request by mrv777**
### Description:

- Show current suffix for temp points on the chart and add the suffix to the axes.
- Make the average hashrate a little easier to see
- Add a 5.0v marker on the input voltage progress bar

### CODE REVIEW

**Comment by skot** [comment]
I got the following warning from node.js when compiling... I don't think we had this before?

```
(node:69549) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by skot** [comment]
looking good! 
image

**Comment by mrv777** [comment]
> I got the following warning from node.js when compiling... I don't think we had this before?
> 
> ```
> (node:69549) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
> (Use `node --trace-deprecation ...` to show where the warning was created)
> ```

That seems to be coming from the script: only-gzip.js

**Comment by skot** [comment]
> > I got the following warning from node.js when compiling... I don't think we had this before?
> > ```
> > (node:69549) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
> > (Use `node --trace-deprecation ...` to show where the warning was created)
> > ```
> 
> That seems to be coming from the script: only-gzip.js

Ah, ok. I see it happens on master too. I'll figure out where that came from.

**Pull request merged**
