### PR TITLE
Add uptime to home screen

### PR DESCRIPTION
**Pull request by mutatrum**
Also expanded the uptime to all units and re-aligned the three dial boxes.

image

### CODE REVIEW

**Review by WantClue — APPROVED** [review]
Testing later today

**Comment by skot** [comment]
@mutatrum we had a ton of UI changes in the last couple days. Can you rebase your uptime changes to the latest UI in master?

**Comment by mutatrum** [comment]
Rebased to new theme:

image

**Comment by skot** [comment]
Beautiful, thank you!

**Review by WantClue — APPROVED** [review]

**Pull request merged**
